var map_settings = {
        base_svg_width: 425,
        base_svg_height: 386,
        base_stroke_width: 1.1,
        mod_font_size: .023,
        mod_font_size_lables: .026,
        bigger_map: !1
    },
	
    quiz = {
        title: "India - Andhra Pradesh - Districts",
        hide: ["place"],
        quiz_items: ["South_Goa", "North_Goa", "Gondia", "Nagpur", "Akola", "Nanded", "Jalna", "Ahmadnagar", "Pune", "Parbhani", "Aurangabad", "Sangli", "Jalgaon", "Ratnagiri", "Thane", "Dhule", "Chandrapur", "Kolhapur", "Solapur", "Latur", "Yavatmal", "Nandurbar", "Nashik", "Sindhudurg", "Raigad", "Palaghar", "Satara", "Beed", "Hingoli", "Usmanabad", "Washim", "Buldhana", "Amaravati", "Wardha", "Bhandara", "Gadchiroli", "Mumbai_City", "Mumbai_Suburban"],
        noquiz_regions: [],
		lang_options: ["en"]
    },
	
    questions = [
	{item_id: "South_Goa", type: "region",item_title: {en: "South_Goa"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "North_Goa", type: "region",item_title: {en: "North_Goa"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Gondia", type: "region",item_title: {en: "Gondia"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Nagpur", type: "region",item_title: {en: "Nagpur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Akola", type: "region",item_title: {en: "Akola"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Nanded", type: "region",item_title: {en: "Nanded"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Jalna", type: "region",item_title: {en: "Jalna"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Ahmadnagar", type: "region",item_title: {en: "Ahmadnagar"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Pune", type: "region",item_title: {en: "Pune"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Parbhani", type: "region",item_title: {en: "Parbhani"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Aurangabad", type: "region",item_title: {en: "Aurangabad"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Sangli", type: "region",item_title: {en: "Sangli"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Jalgaon", type: "region",item_title: {en: "Jalgaon"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Ratnagiri", type: "region",item_title: {en: "Ratnagiri"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Thane", type: "region",item_title: {en: "Thane"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Dhule", type: "region",item_title: {en: "Dhule"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Chandrapur", type: "region",item_title: {en: "Chandrapur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Kolhapur", type: "region",item_title: {en: "Kolhapur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Solapur", type: "region",item_title: {en: "Solapur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Latur", type: "region",item_title: {en: "Latur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Yavatmal", type: "region",item_title: {en: "Yavatmal"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Nandurbar", type: "region",item_title: {en: "Nandurbar"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Nashik", type: "region",item_title: {en: "Nashik"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Sindhudurg", type: "region",item_title: {en: "Sindhudurg"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Raigad", type: "region",item_title: {en: "Raigad"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Palaghar", type: "region",item_title: {en: "Palaghar"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Satara", type: "region",item_title: {en: "Satara"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Beed", type: "region",item_title: {en: "Beed"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Hingoli", type: "region",item_title: {en: "Hingoli"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Usmanabad", type: "region",item_title: {en: "Usmanabad"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Washim", type: "region",item_title: {en: "Washim"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Buldhana", type: "region",item_title: {en: "Buldhana"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Amaravati", type: "region",item_title: {en: "Amaravati"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Wardha", type: "region",item_title: {en: "Wardha"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Bhandara", type: "region",item_title: {en: "Bhandara"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Gadchiroli", type: "region",item_title: {en: "Gadchiroli"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Mumbai_City", type: "region",item_title: {en: "Mumbai_City"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Mumbai_Suburban", type: "region",item_title: {en: "Mumbai_Suburban"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	];