var map_settings = {
        base_svg_width: 285,
        base_svg_height: 175,
        base_stroke_width: 1.1,
        mod_font_size: .023,
        mod_font_size_lables: .026,
        bigger_map: !1
    },
	
    quiz = {
        title: "India - Andhra Pradesh - Districts",
        hide: ["place"],
        quiz_items: ["Samastipur", "Saran", "Siwan", "Darbhanga", "Sitamarhi", "Sheohar", "Vaishali", "Jamui", "Banka", "Nalanda", "Begusarai", "East_Champaran", "Saharsa", "Purnia", "Katihar", "Madhepura", "Lakhisarai", "Sheikhpura", "Khagaria", "Bhagalpur", "Supaul", "Nawada", "Munger", "Madhubani", "Jehanabad", "Aurangabad", "Patna", "Bhojpur", "Rohtas", "Buxar", "Muzaffarpur", "Arwal", "Gopalganj", "Araria", "Gaya", "Kaimur", "Kishanganj", "West_Champaran"],
        noquiz_regions: [],
		lang_options: ["en"]
    },
	
    questions = [
	{item_id: "Samastipur", type: "region",item_title: {en: "Samastipur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Saran", type: "region",item_title: {en: "Saran"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Siwan", type: "region",item_title: {en: "Siwan"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Darbhanga", type: "region",item_title: {en: "Darbhanga"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Sitamarhi", type: "region",item_title: {en: "Sitamarhi"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Sheohar", type: "region",item_title: {en: "Sheohar"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Vaishali", type: "region",item_title: {en: "Vaishali"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Jamui", type: "region",item_title: {en: "Jamui"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Banka", type: "region",item_title: {en: "Banka"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Nalanda", type: "region",item_title: {en: "Nalanda"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Begusarai", type: "region",item_title: {en: "Begusarai"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "East_Champaran", type: "region",item_title: {en: "East_Champaran"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Saharsa", type: "region",item_title: {en: "Saharsa"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Purnia", type: "region",item_title: {en: "Purnia"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Katihar", type: "region",item_title: {en: "Katihar"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Madhepura", type: "region",item_title: {en: "Madhepura"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Lakhisarai", type: "region",item_title: {en: "Lakhisarai"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Sheikhpura", type: "region",item_title: {en: "Sheikhpura"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Khagaria", type: "region",item_title: {en: "Khagaria"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Bhagalpur", type: "region",item_title: {en: "Bhagalpur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Supaul", type: "region",item_title: {en: "Supaul"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Nawada", type: "region",item_title: {en: "Nawada"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Munger", type: "region",item_title: {en: "Munger"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Madhubani", type: "region",item_title: {en: "Madhubani"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Jehanabad", type: "region",item_title: {en: "Jehanabad"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Aurangabad", type: "region",item_title: {en: "Aurangabad"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Patna", type: "region",item_title: {en: "Patna"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Bhojpur", type: "region",item_title: {en: "Bhojpur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Rohtas", type: "region",item_title: {en: "Rohtas"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Buxar", type: "region",item_title: {en: "Buxar"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Muzaffarpur", type: "region",item_title: {en: "Muzaffarpur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Arwal", type: "region",item_title: {en: "Arwal"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Gopalganj", type: "region",item_title: {en: "Gopalganj"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Araria", type: "region",item_title: {en: "Araria"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Gaya", type: "region",item_title: {en: "Gaya"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Kaimur", type: "region",item_title: {en: "Kaimur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Kishanganj", type: "region",item_title: {en: "Kishanganj"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "West_Champaran", type: "region",item_title: {en: "West_Champaran"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}}
	];