var map_settings = {
        base_svg_width: 316,
        base_svg_height: 289,
        base_stroke_width: 1.1,
        mod_font_size: .023,
        mod_font_size_lables: .026,
        bigger_map: !1
    },
	
    quiz = {
        title: "India - Andhra Pradesh - Districts",
        hide: ["place"],
        quiz_items: ["Bharuch","Narmada","Surat","Vadodara","Botad","Dahod","Panchmahal","Kheda","Junagadh","Ahmedabad","Bhavnagar","Surendranagar","Mehsana","Morbi","Jamnagar","Porbandar","Gir_Somnath","Amreli","Gandhinagar","Anand","Rajkot","Patan","Tapi","Chhota_Udaipur","Mahisagar","Banaskantha","Devbhoomi_Dwarka","Navsari","Aravalli","Valsad","Dang","Sabarkantha","Kutch","Dadar_and_Nagar_haveli","Diu","Daman"],
        noquiz_regions: [],
		lang_options: ["en"]
    },
	
    questions = [
	{item_id: "Bharuch", type: "region",item_title: {en: "Bharuch"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Narmada", type: "region",item_title: {en: "Narmada"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Surat", type: "region",item_title: {en: "Surat"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Vadodara", type: "region",item_title: {en: "Vadodara"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Botad", type: "region",item_title: {en: "Botad"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Dahod", type: "region",item_title: {en: "Dahod"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Panchmahal", type: "region",item_title: {en: "Panchmahal"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Kheda", type: "region",item_title: {en: "Kheda"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Junagadh", type: "region",item_title: {en: "Junagadh"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Ahmedabad", type: "region",item_title: {en: "Ahmedabad"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Bhavnagar", type: "region",item_title: {en: "Bhavnagar"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Surendranagar", type: "region",item_title: {en: "Surendranagar"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Mehsana", type: "region",item_title: {en: "Mehsana"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Morbi", type: "region",item_title: {en: "Morbi"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Jamnagar", type: "region",item_title: {en: "Jamnagar"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Porbandar", type: "region",item_title: {en: "Porbandar"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Gir_Somnath", type: "region",item_title: {en: "Gir_Somnath"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Amreli", type: "region",item_title: {en: "Amreli"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Gandhinagar", type: "region",item_title: {en: "Gandhinagar"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Anand", type: "region",item_title: {en: "Anand"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Rajkot", type: "region",item_title: {en: "Rajkot"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Patan", type: "region",item_title: {en: "Patan"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Tapi", type: "region",item_title: {en: "Tapi"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Chhota_Udaipur", type: "region",item_title: {en: "Chhota_Udaipur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Mahisagar", type: "region",item_title: {en: "Mahisagar"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Banaskantha", type: "region",item_title: {en: "Banaskantha"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Devbhoomi_Dwarka", type: "region",item_title: {en: "Devbhoomi_Dwarka"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Navsari", type: "region",item_title: {en: "Navsari"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Aravalli", type: "region",item_title: {en: "Aravalli"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Valsad", type: "region",item_title: {en: "Valsad"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Dang", type: "region",item_title: {en: "Dang"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Sabarkantha", type: "region",item_title: {en: "Sabarkantha"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Kutch", type: "region",item_title: {en: "Kutch"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Dadar_and_Nagar_haveli", type: "region",item_title: {en: "Dadar_and_Nagar_haveli"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Diu", type: "region",item_title: {en: "Diu"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Daman", type: "region",item_title: {en: "Daman"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	];