var map_settings = {
        base_svg_width: 372,
        base_svg_height: 349,
        base_stroke_width: 1.1,
        mod_font_size: .023,
        mod_font_size_lables: .026,
        bigger_map: !1
    },
	
    quiz = {
        title: "India - Andhra Pradesh - Districts",
        hide: ["place"],
        quiz_items: ["Bijnor", "Lalitpur", "Kushinagar", "Siddarthnagar", "Shravasti", "Kaushambi", "Kannauj", "Firozabad", "Mathura", "Badaun", "Moradabad", "Hapur", "Bulandshahr", "Muzaffarnagar", "Meerut", "Ghaziabad", "Fatehpur", "Agra", "Gautam_Buddh_Nagar", "Shamli", "Baghpat", "Farrukhabad", "Hathras", "Shahjahanpur", "Rampur", "Pilbhit", "Sambhal", "Sonbhadra", "Chandauli", "Lucknow", "Auraiya", "Kanpur_Nagar", "Sitapur", "Hardoi", "Mainpuri", "Etah", "Jaunpur", "Bhadohi", "Prayagraj", "Mirzapur", "Varanasi", "Lakhimpur_Kheri", "Deoria", "Ballia", "Azamgarh", "Mau", "Sant_Kabir_Nagar", "Ghazipur", "Ayodhya", "Amethi", "Gonda", "Kanpur_Dehat", "Banda", "Pratapgarh", "Mahoba", "Kasganj", "Bareilly", "Aligarh", "Saharanpur", "Amroha", "Jhansi", "Jalaun", "Unnao", "Barabanki", "Etawah", "Ambedkar_Nagar", "Maharajganj", "Balrampur", "Basti", "Gorakhpur", "Bahraich", "Chitrakoot", "Hamirpur", "Sultanpur", "Rae_Bareli"],
        noquiz_regions: [],
		lang_options: ["en"]
    },
	
    questions = [
	{item_id: "Bijnor", type: "region",item_title: {en: "Bijnor"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Lalitpur", type: "region",item_title: {en: "Lalitpur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Kushinagar", type: "region",item_title: {en: "Kushinagar"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Siddarthnagar", type: "region",item_title: {en: "Siddarthnagar"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Shravasti", type: "region",item_title: {en: "Shravasti"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Kaushambi", type: "region",item_title: {en: "Kaushambi"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Kannauj", type: "region",item_title: {en: "Kannauj"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Firozabad", type: "region",item_title: {en: "Firozabad"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Mathura", type: "region",item_title: {en: "Mathura"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Badaun", type: "region",item_title: {en: "Badaun"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Moradabad", type: "region",item_title: {en: "Moradabad"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Hapur", type: "region",item_title: {en: "Hapur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Bulandshahr", type: "region",item_title: {en: "Bulandshahr"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Muzaffarnagar", type: "region",item_title: {en: "Muzaffarnagar"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Meerut", type: "region",item_title: {en: "Meerut"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Ghaziabad", type: "region",item_title: {en: "Ghaziabad"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Fatehpur", type: "region",item_title: {en: "Fatehpur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Agra", type: "region",item_title: {en: "Agra"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Gautam_Buddh_Nagar", type: "region",item_title: {en: "Gautam_Buddh_Nagar"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Shamli", type: "region",item_title: {en: "Shamli"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Baghpat", type: "region",item_title: {en: "Baghpat"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Farrukhabad", type: "region",item_title: {en: "Farrukhabad"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Hathras", type: "region",item_title: {en: "Hathras"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Shahjahanpur", type: "region",item_title: {en: "Shahjahanpur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Rampur", type: "region",item_title: {en: "Rampur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Pilbhit", type: "region",item_title: {en: "Pilbhit"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Sambhal", type: "region",item_title: {en: "Sambhal"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Sonbhadra", type: "region",item_title: {en: "Sonbhadra"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Chandauli", type: "region",item_title: {en: "Chandauli"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Lucknow", type: "region",item_title: {en: "Lucknow"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Auraiya", type: "region",item_title: {en: "Auraiya"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Kanpur_Nagar", type: "region",item_title: {en: "Kanpur_Nagar"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Sitapur", type: "region",item_title: {en: "Sitapur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Hardoi", type: "region",item_title: {en: "Hardoi"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Mainpuri", type: "region",item_title: {en: "Mainpuri"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Etah", type: "region",item_title: {en: "Etah"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Jaunpur", type: "region",item_title: {en: "Jaunpur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Bhadohi", type: "region",item_title: {en: "Bhadohi"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Prayagraj", type: "region",item_title: {en: "Prayagraj"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Mirzapur", type: "region",item_title: {en: "Mirzapur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Varanasi", type: "region",item_title: {en: "Varanasi"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Lakhimpur_Kheri", type: "region",item_title: {en: "Lakhimpur_Kheri"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Deoria", type: "region",item_title: {en: "Deoria"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Ballia", type: "region",item_title: {en: "Ballia"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Azamgarh", type: "region",item_title: {en: "Azamgarh"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Mau", type: "region",item_title: {en: "Mau"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Sant_Kabir_Nagar", type: "region",item_title: {en: "Sant_Kabir_Nagar"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Ghazipur", type: "region",item_title: {en: "Ghazipur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Ayodhya", type: "region",item_title: {en: "Ayodhya"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Amethi", type: "region",item_title: {en: "Amethi"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Gonda", type: "region",item_title: {en: "Gonda"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Kanpur_Dehat", type: "region",item_title: {en: "Kanpur_Dehat"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Banda", type: "region",item_title: {en: "Banda"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Pratapgarh", type: "region",item_title: {en: "Pratapgarh"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Mahoba", type: "region",item_title: {en: "Mahoba"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Kasganj", type: "region",item_title: {en: "Kasganj"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Bareilly", type: "region",item_title: {en: "Bareilly"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Aligarh", type: "region",item_title: {en: "Aligarh"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Saharanpur", type: "region",item_title: {en: "Saharanpur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Amroha", type: "region",item_title: {en: "Amroha"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Jhansi", type: "region",item_title: {en: "Jhansi"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Jalaun", type: "region",item_title: {en: "Jalaun"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Unnao", type: "region",item_title: {en: "Unnao"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Barabanki", type: "region",item_title: {en: "Barabanki"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Etawah", type: "region",item_title: {en: "Etawah"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Ambedkar_Nagar", type: "region",item_title: {en: "Ambedkar_Nagar"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Maharajganj", type: "region",item_title: {en: "Maharajganj"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Balrampur", type: "region",item_title: {en: "Balrampur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Basti", type: "region",item_title: {en: "Basti"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Gorakhpur", type: "region",item_title: {en: "Gorakhpur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Bahraich", type: "region",item_title: {en: "Bahraich"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Chitrakoot", type: "region",item_title: {en: "Chitrakoot"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Hamirpur", type: "region",item_title: {en: "Hamirpur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Sultanpur", type: "region",item_title: {en: "Sultanpur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Rae_Bareli", type: "region",item_title: {en: "Rae_Bareli"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	];