var map_settings = {
        base_svg_width: 450,
        base_svg_height: 330,
        base_stroke_width: 1.1,
        mod_font_size: .020,
        mod_font_size_lables: .026,
        bigger_map: !1
    },
	
    quiz = {
        title: "India - Andhra Pradesh - Districts",
        hide: ["place"],
        quiz_items: ["Singrauli", "Chhindwara", "Satna", "Dindori", "Damoh", "Hoshangabad", "Betul", "Seoni", "Narsinghpur", "Rewa", "Katni", "Umaria", "Harda", "Shahdol", "Khandwa", "Mandla", "Khargone", "Barwani", "Dewas", "Ujjain", "Raisen", "Bhopal", "Guna", "Shajapur", "Ratlam", "Jhabua", "Agar_Malwa", "Rajgarh", "Sehore", "Vidisha", "Jabalpur", "Sagar", "Alirajpur", "Dhar", "Indore", "Anuppur", "Panna", "Ashoknagar", "Chhatarpur", "Burhanpur", "Balaghat", "Neemuch", "Sidhi", "Niwari", "Gwalior", "Morena", "Datia", "Bhind", "Sheopur", "Mandsaur", "Tikamgarh", "Shivpuri"],
        noquiz_regions: [],
		lang_options: ["en"]
    },
	
    questions = [
	{item_id: "Singrauli", type: "region",item_title: {en: "Singrauli"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Chhindwara", type: "region",item_title: {en: "Chhindwara"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Satna", type: "region",item_title: {en: "Satna"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Dindori", type: "region",item_title: {en: "Dindori"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Damoh", type: "region",item_title: {en: "Damoh"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Hoshangabad", type: "region",item_title: {en: "Hoshangabad"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Betul", type: "region",item_title: {en: "Betul"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Seoni", type: "region",item_title: {en: "Seoni"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Narsinghpur", type: "region",item_title: {en: "Narsinghpur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Rewa", type: "region",item_title: {en: "Rewa"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Katni", type: "region",item_title: {en: "Katni"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Umaria", type: "region",item_title: {en: "Umaria"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Harda", type: "region",item_title: {en: "Harda"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Shahdol", type: "region",item_title: {en: "Shahdol"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Khandwa", type: "region",item_title: {en: "Khandwa"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Mandla", type: "region",item_title: {en: "Mandla"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Khargone", type: "region",item_title: {en: "Khargone"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Barwani", type: "region",item_title: {en: "Barwani"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Dewas", type: "region",item_title: {en: "Dewas"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Ujjain", type: "region",item_title: {en: "Ujjain"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Raisen", type: "region",item_title: {en: "Raisen"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Bhopal", type: "region",item_title: {en: "Bhopal"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Guna", type: "region",item_title: {en: "Guna"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Shajapur", type: "region",item_title: {en: "Shajapur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Ratlam", type: "region",item_title: {en: "Ratlam"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Jhabua", type: "region",item_title: {en: "Jhabua"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Agar_Malwa", type: "region",item_title: {en: "Agar_Malwa"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Rajgarh", type: "region",item_title: {en: "Rajgarh"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Sehore", type: "region",item_title: {en: "Sehore"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Vidisha", type: "region",item_title: {en: "Vidisha"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Jabalpur", type: "region",item_title: {en: "Jabalpur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Sagar", type: "region",item_title: {en: "Sagar"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Alirajpur", type: "region",item_title: {en: "Alirajpur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Dhar", type: "region",item_title: {en: "Dhar"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Indore", type: "region",item_title: {en: "Indore"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Anuppur", type: "region",item_title: {en: "Anuppur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Panna", type: "region",item_title: {en: "Panna"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Ashoknagar", type: "region",item_title: {en: "Ashoknagar"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Chhatarpur", type: "region",item_title: {en: "Chhatarpur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Burhanpur", type: "region",item_title: {en: "Burhanpur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Balaghat", type: "region",item_title: {en: "Balaghat"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Neemuch", type: "region",item_title: {en: "Neemuch"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Sidhi", type: "region",item_title: {en: "Sidhi"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Niwari", type: "region",item_title: {en: "Niwari"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Gwalior", type: "region",item_title: {en: "Gwalior"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Morena", type: "region",item_title: {en: "Morena"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Datia", type: "region",item_title: {en: "Datia"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Bhind", type: "region",item_title: {en: "Bhind"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Sheopur", type: "region",item_title: {en: "Sheopur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Mandsaur", type: "region",item_title: {en: "Mandsaur"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Tikamgarh", type: "region",item_title: {en: "Tikamgarh"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}},
	{item_id: "Shivpuri", type: "region",item_title: {en: "Shivpuri"}, link_wikipedia: {en: "https://en.wikipedia.org/wiki/Tirupati_district"}}
	];